In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Andre statiske modeller 

I dette dokument undersøger vi tre andre modeller som kan blive brugt til binær klassificering. Ved undersøgelse af disse modeller er konklusionen at resultaterne er lige så gode som fra logistisk regression. Grunden bag at vi valgte  logistisk regression er at den er hurtig og effektiv. 

In [3]:
df = pd.read_csv('Behandlet data-kopi.csv', sep=';', header=0, index_col=0, decimal=',')
df

Anteroposterior 1.1  Anteroposterior 1.2  Vertical 1.1  Vertical 1.2  \
1                    9.0                  0.0           0.0           0.0   
2                    9.0                  0.0           0.0           0.0   
3                    0.0                  0.0           0.0           0.0   
4                    9.0                  0.0           1.0           0.0   
5                    0.0                  0.0           0.0           0.0   
..                   ...                  ...           ...           ...   
117                 12.0                  0.0           3.0           1.0   
118                  9.0                  0.0           1.0           0.0   
119                  9.0                  0.0           4.0           0.0   
120                 12.0                  0.0           0.0           0.0   
122                  9.0                  1.0           0.0           0.0   

     Transverse 1  Crowding 1  Spacing 1  Tooth shape/size 1  Pan 1  \
1             6.0         0.0        4.0                 0.0    4.0   
2             6.0         1.0        1.0                 1.0    3.0   
3             2.0         3.0        1.0                 0.0    4.0   
4             6.0         4.0        0.0                 1.0    4.0   
5             6.0         0.0        0.0                 0.0    4.0   
..            ...         ...        ...                 ...    ...   
117           6.0         4.0        0.0                 1.0    4.0   
118           6.0         0.0        3.0                 0.0    4.0   
119           0.0         4.0        0.0                 0.0    4.0   
120           6.0         3.0        0.0                 0.0    4.0   
122           6.0         3.0        0.0                 0.0    4.0   

     Anteroposterior 2.1  Anteroposterior 2.2  Vertical 2.1  Vertical 2.2  \
1                    0.0                  0.0           0.0           0.0   
2                    9.0                  0.0           2.0           4.0   
3                    0.0                  0.0           0.0           0.0   
4                    9.0                  0.0           2.0           0.0   
5                    0.0                  0.0           0.0           0.0   
..                   ...                  ...           ...           ...   
117                  9.0                  0.0           0.0           0.0   
118                  9.0                  0.0           0.0           0.0   
119                 12.0                  0.0           3.0           4.0   
120                  9.0                  0.0           0.0           0.0   
122                 12.0                  3.0           2.0           3.0   

     Transverse 2  Crowding 2  Spacing 2  Tooth shape/size 2  Pan 2  \
1             6.0         0.0        4.0                 0.0    3.0   
2             6.0         0.0        0.0                 1.0    3.0   
3             6.0         1.0        3.0                 0.0    0.0   
4             6.0         4.0        0.0                 1.0    4.0   
5             2.0         0.0        4.0                 0.0    3.0   
..            ...         ...        ...                 ...    ...   
117           6.0         3.0        0.0                 1.0    0.0   
118           6.0         0.0        3.0                 0.0    3.0   
119           6.0         4.0        0.0                 0.0    3.0   
120           6.0         4.0        0.0                 0.0    4.0   
122           6.0         3.0        0.0                 1.0    4.0   

     Total Row Score C  
1                    0  
2                    8  
3                    9  
4                    9  
5                   13  
..                 ...  
117                  3  
118                  3  
119                  4  
120                 12  
122                  6  

[117 rows x 19 columns]

In [4]:
def pin_update(row):
    if row["Total Row Score C"] <= 5:
        return 0
    else:
        return 1

In [5]:
Output = df.apply(pin_update, axis=1)

df['Output'] = Output


df1 = df[["Anteroposterior 1.1",
          'Anteroposterior 1.2',
          'Vertical 1.1',
          'Vertical 1.2',
          'Transverse 1',
          'Crowding 1',
          'Spacing 1',
          'Tooth shape/size 1',
          'Pan 1',
          'Anteroposterior 2.1',
          'Anteroposterior 2.2',
          'Vertical 2.1',
          'Vertical 2.2',
          'Transverse 2',
          'Crowding 2',
          'Spacing 2',
          'Tooth shape/size 2',
           'Pan 2',
          'Output']]



df1 = df1.iloc[1:, :]

df1 = df1.dropna()

target_column = ["Output"]
numerical_column = df1.columns.drop(target_column)
output_rows = df1[target_column]
df1.drop(target_column,axis=1,inplace=True)

scaler = MinMaxScaler()
df1 = scaler.fit_transform(df1)

X_train, X_test, y_train, y_test = train_test_split(df1, output_rows, test_size=0.25, shuffle=True)

In [6]:
acc = []
prediction = []
confusion_matrix = []

from sklearn.ensemble import RandomForestClassifier

for i in range(25):
    X_train, X_test, y_train, y_test = train_test_split(df1, output_rows, test_size=0.25, shuffle=True)
    
    clf = RandomForestClassifier()
    
    clf = clf.fit(X_train, y_train.values.ravel())
    
    pre = clf.predict(X_test)
    
    cm = metrics.confusion_matrix(y_test, pre)
    
    acc.append(clf.score(X_test, y_test))
    confusion_matrix.append(cm)
    prediction.append(pre)
    
print(f"Accuracy: {np.mean(np.array(acc))}")
print(f"Confusion matrix: \n {sum(confusion_matrix)}")



Accuracy: 0.6344827586206897
Confusion matrix: 
 [[230 125]
 [140 230]]


In [7]:
xnew = np.array([[12, 0,0,0,8,2,0,1,4,
                  12,2,0,4,8,3,0,0,4]])

xnew = scaler.transform(xnew)
clf.predict_proba(xnew)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.16, 0.84]])

In [8]:
acc = []
prediction = []
confusion_matrix = []

from sklearn.tree import DecisionTreeClassifier
for i in range(25):
    X_train, X_test, y_train, y_test = train_test_split(df1, output_rows, test_size=0.25, shuffle=True)
    
    clf = DecisionTreeClassifier()
    
    clf = clf.fit(X_train, y_train.values.ravel())
    
    pre = clf.predict(X_test)
    
    cm = metrics.confusion_matrix(y_test, pre)
    
    acc.append(clf.score(X_test, y_test))
    confusion_matrix.append(cm)
    prediction.append(pre)
    
print(f"Accuracy: {np.mean(np.array(acc))}")
print(f"Confusion matrix: \n {sum(confusion_matrix)}")


Accuracy: 0.6041379310344829
Confusion matrix: 
 [[231 139]
 [148 207]]


In [9]:
xnew = np.array([[12, 0,0,0,8,2,0,1,4,
                  12,2,0,4,8,3,0,0,4]])

xnew = scaler.transform(xnew)

clf.predict_proba(xnew)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [10]:

acc = []
prediction = []
confusion_matrix = []

from sklearn.neighbors import KNeighborsClassifier

for i in range(25):
    X_train, X_test, y_train, y_test = train_test_split(df1, output_rows, test_size=0.25, shuffle=True)
    
    clf = KNeighborsClassifier()
    
    clf = clf.fit(X_train, y_train.values.ravel())
    
    pre = clf.predict(X_test)
    
    cm = metrics.confusion_matrix(y_test, pre)
    
    acc.append(clf.score(X_test, y_test))
    confusion_matrix.append(cm)
    prediction.append(pre)
    
print(f"Accuracy: {np.mean(np.array(acc))}")
print(f"Confusion matrix: \n {sum(confusion_matrix)}")


Accuracy: 0.670344827586207
Confusion matrix: 
 [[251 129]
 [110 235]]


In [11]:
xnew = np.array([[12, 0,0,0,8,2,0,1,4,
                  12,2,0,4,8,3,0,0,4]])

xnew = scaler.transform(xnew)

clf.predict_proba(xnew)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0., 1.]])